{% set name = "PETPVC" %}
{% set version = "1.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL/PETPVC/archive/v{{ version }}.tar.gz
  sha256: 3a53e26ee4ebd9efea8804f3516b230c1328c38de3e8e2ba3f901da4437554ee

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libitk-devel
  run:
    - libitk

test:
  commands:
    - petpvc  # [not win]

about:
  home: https://github.com/UCL/PETPVC
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Toolbox for partial volume correction (PVC) in positron emission tomography (PET)

extra:
  recipe-maintainers:
    - ghisvail
